### PR TITLE
add Xcode 12 with iOS 14 support proposal

### PR DESCRIPTION
**Pull request by onmotion**

### CODE REVIEW

**Comment by thellimist** [comment]
I'm not familiar with this change. Can someone who knows ios14 confirm the changes are correct?

**Comment by onmotion** [comment]
Hi

Just try to make a new project, then add the pod and build the project

image

**Comment by thellimist** [comment]
I'll wait confirmation from another person who can review the code. Till then, this can stay as a branch

**Comment by zane-carter** [comment]
These changes are correct. Can we merge this?

**Comment by thellimist** [comment]
@zane-carter merged and created a release. 

I don't remember how to release to pods. It's been 8 years since I have coded iOS. Hopefully Github tagging would work for you :)

**Pull request merged**
