### PR TITLE
Added Objective-C support for EZAlertController class

### PR DESCRIPTION
**Pull request by ShadeApps**
#25

### CODE REVIEW

**Comment by thellimist** [comment]
Does this change effect swift users in anyway?

**Comment by ShadeApps** [comment]
I've tested it on this [little test project](https://www.dropbox.com/s/jg2chqey5g67qbe/TestEZAlertApp.zip?dl=0) for Swift 3.0 on Xcode 8.2 without any Objective-C code and it works just as it used to.

**Comment by thellimist** [comment]
Looks good thanks. I think we don't need a new release for this addition. After a few more changes happen to the repository I'll do a new pod release. Does this sound good?

**Comment by ShadeApps** [comment]
Great, thank you!

**Pull request merged**
