### PR TITLE
Updated Readme.

### PR DESCRIPTION
**Pull request by anand2nigam**
I have updated readme but I think, you need to update the image below it too. 
Thanks and Regards.

### CODE REVIEW

**Comment by thellimist** [comment]
Looks great! Can you take a gif of your work and upload that as well?

Thanks

**Comment by anand2nigam** [comment]
I am afraid, I can not do that, can you not merge that without the gif? Or is it mandatory to make the gif for the merge?

**Comment by thellimist** [comment]
I'd prefer the gif to be included. With small googling you can find good tools to capture gifs on the screen (on computer).

**Comment by anand2nigam** [comment]
Hey, I have added the image, I hope this works, kindly do the merge now.

**Comment by thellimist** [comment]
Looks great. One last thing would be dividing each component into its own section like:

```
EZAlertController.alert("Title", message: "Message", buttons: ["First", "Second"]) { (alertAction, position) -> Void in
    if position == 0 {
        print("First button clicked")
    } else if position == 1 {
        print("Second button clicked")
    }
}
```

IMG1

```
// With Preferred Button Style along with all alerts in a single closure
// Here the Logout button will be red in color to show that it is a destructive action
EZAlertController.alert("Title", message: "Message", buttons: ["Cancel","Logout"], buttonsPreferredStyle:[.default, .destructive]) { (alert, position) in 
    if position == 0 {
        print("Cancel button clicked")
    } else if position == 1 {
        print("Logout button clicked")
    }
}
```

IMG2

---

Thanks!

**Comment by anand2nigam** [comment]
Done.

**Pull request merged**
